services:
  otelhttpservice:
    image: otel-testing:local
    build:
      context: .
    environment:
      APP_POSTGRES_HOST: postgres
      APP_POSTGRES_PASSWORD: oteltesting
      APP_OTEL_ENABLE: false
    ports:
      - "8080:8080"

  postgres:
    image: postgres:14.12-alpine3.19
    environment:
      POSTGRES_PASSWORD: oteltesting
    configs:
      - source: postgres-schema
        target: /docker-entrypoint-initdb.d/schema.sql
    volumes:
      - postgres-data:/var/lib/mysql

configs:
  postgres-schema:
    file: sql/schema.sql

volumes:
  postgres-data:
